service: service-anotaai

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket: deploy-bucket-loocal-lambda
  region: us-east-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"

functions:
  api:
    description: "API Serverless para integração com AnotaAi"
    handler: src/lambda.handler
    environment:
      DB_USER: ${self:custom.${self:provider.stage}.DB_USER}
      DB_PASSWORD: ${self:custom.${self:provider.stage}.DB_PASSWORD}
      DB_HOST: ${self:custom.${self:provider.stage}.DB_HOST}
      DB_NAME: ${self:custom.${self:provider.stage}.DB_NAME}
      DB_PORT: ${self:custom.${self:provider.stage}.DB_PORT}
      CLIENT_ID: ${self:custom.${self:provider.stage}.CLIENT_ID}
      CLIENT_SECRET: ${self:custom.${self:provider.stage}.CLIENT_SECRET}
      ANOTA_AI_URL: ${self:custom.${self:provider.stage}.ANOTA_AI_URL}
      LOOCAL_API_URL: ${self:custom.${self:provider.stage}.LOOCAL_API_URL}
      TOKEN_LOOCAL: ${self:custom.${self:provider.stage}.TOKEN_LOOCAL}
      URL_LAMBDA_ANOTA_AI: ${self:custom.${self:provider.stage}.URL_LAMBDA_ANOTA_AI}
      GOOGLE_MAPS_API_KEY: ${self:custom.${self:provider.stage}.GOOGLE_MAPS_API_KEY}
    timeout: 60
    memorySize: 256
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  dev:
    stage: "dev"
    DB_USER: postgres
    DB_PASSWORD:
    DB_HOST:
    DB_NAME: development
    DB_PORT: 5432
    CLIENT_ID:
    CLIENT_SECRET:
    ANOTA_AI_URL: https://api-parceiros.anota.ai/partnerauth
    LOOCAL_API_URL: https://api-developer-v3.loocalapp.com/api
    TOKEN_LOOCAL:
    URL_LAMBDA_ANOTA_AI: https://3qqize8sc1.execute-api.us-east-1.amazonaws.com/dev/api
    GOOGLE_MAPS_API_KEY:

  prd:
    stage: "prod"
    DB_USER: postgres
    DB_PASSWORD:
    DB_HOST:
    DB_NAME: postgres
    DB_PORT: 5432
    CLIENT_ID:
    CLIENT_SECRET:
    ANOTA_AI_URL: https://api-parceiros.anota.ai/partnerauth
    LOOCAL_API_URL: https://api-production-v3.loocalapp.com/api/
    TOKEN_LOOCAL:
    URL_LAMBDA_ANOTA_AI: https://tga54kkmmc.execute-api.us-east-1.amazonaws.com/prd/api
    GOOGLE_MAPS_API_KEY:

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  excludeDevDependencies: true
  exclude:
    - .vscode/**
    - '*/**/*.js.map'
    - coverage/**
    - dist/test/**
    - lib/**
    - temp/**
    - test/**
    - .git/**
    - docs/**
    - .github/**
    - .key.txt
    - deploy.txt
